# Generated by Django 5.0.2 on 2024-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dis_count_availave',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='parcentage_of_discount',
            field=models.IntegerField(null=True),
        ),
    ]
