# Generated by Django 5.0.2 on 2024-02-27 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_food_dis_count_availave_food_parcentage_of_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='bought_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='commentors',
            field=models.ManyToManyField(blank=True, related_name='comment_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
