# Generated by Django 5.0.2 on 2024-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_food_buyers_food_commentors_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='parcentage_of_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
