# Generated by Django 5.0.2 on 2024-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_food_parcentage_of_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_img',
            field=models.ImageField(upload_to='photos/foodes'),
        ),
    ]
