# Generated by Django 5.0.2 on 2024-02-27 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviews_unique_together_alter_reviews_rating'),
        ('store', '0007_food_buyers_food_commentors_delete_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('food', 'user')},
        ),
    ]
