# Generated by Django 5.0.2 on 2024-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
