# Generated by Django 5.0.2 on 2024-02-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_item_done'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='order.order'),
        ),
    ]
