# Generated by Django 5.0.2 on 2024-02-26 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='z', max_length=100, null=True)),
                ('last_name', models.CharField(default='z', max_length=100, null=True)),
                ('phone', models.CharField(default='z', max_length=12, null=True)),
                ('address_line1', models.CharField(default='z', max_length=100, null=True)),
                ('state', models.CharField(default='z', max_length=100, null=True)),
                ('city', models.CharField(default='z', max_length=100, null=True)),
                ('order_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delevary_cost', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('toatal', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
