# Generated by Django 5.0.2 on 2024-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_total_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='toatal',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
